# Generated by Django 5.1.2 on 2024-10-15 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sellers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_discord", models.CharField(max_length=255)),
                ("name_on_server", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ServerUrls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_name", models.CharField(max_length=255)),
                ("game_name", models.CharField(max_length=255)),
                ("server_url", models.URLField()),
                ("region", models.CharField(max_length=255)),
                ("fraction", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OffersForPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.IntegerField()),
                ("description", models.TextField()),
                ("price", models.CharField(max_length=255)),
                ("stock", models.IntegerField()),
                ("min_units_per_order", models.IntegerField()),
                ("active_rate", models.BooleanField(default=False)),
                ("percent_offset", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("face_to_face_trade", models.BooleanField(default=True)),
                ("mail_delivery", models.BooleanField(default=True)),
                ("auction_house", models.BooleanField(default=True)),
                ("delivery_online_hrs", models.IntegerField()),
                ("delivery_offline_hrs", models.IntegerField()),
                ("is_created_lot", models.BooleanField(default=False)),
                ("reserve_stock", models.IntegerField(default=0)),
                (
                    "sellers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.sellers"
                    ),
                ),
                (
                    "server_urls",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top1", models.IntegerField()),
                ("top5", models.IntegerField()),
                ("top10", models.IntegerField()),
                ("top20", models.IntegerField()),
                ("mean10", models.IntegerField()),
                ("mean20", models.IntegerField()),
                ("minimal", models.IntegerField()),
                ("mean10_lot", models.IntegerField()),
                ("mean20_lot", models.IntegerField()),
                ("double_minimal", models.IntegerField()),
                ("created_time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "server_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
        ),
    ]
