# Generated by Django 5.1.2 on 2025-02-06 22:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commission", models.IntegerField(default=0)),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.DecimalField(decimal_places=3, default=0.07, max_digits=5),
                ),
                (
                    "renter_lvl1",
                    models.DecimalField(decimal_places=3, default=0.05, max_digits=5),
                ),
                (
                    "renter_lvl2",
                    models.DecimalField(decimal_places=3, default=0.1, max_digits=5),
                ),
                (
                    "mentor",
                    models.DecimalField(decimal_places=3, default=0.05, max_digits=5),
                ),
                (
                    "owner",
                    models.DecimalField(decimal_places=3, default=0.05, max_digits=5),
                ),
                (
                    "technical",
                    models.DecimalField(decimal_places=3, default=0.05, max_digits=5),
                ),
                (
                    "recruiter",
                    models.DecimalField(decimal_places=3, default=0.05, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Ставка комісії",
                "verbose_name_plural": "Ставки комісій",
            },
        ),
        migrations.CreateModel(
            name="ServerUrls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_name", models.CharField(max_length=255)),
                ("game_name", models.CharField(max_length=255)),
                ("server_url", models.URLField()),
                ("region", models.CharField(max_length=255)),
                ("fraction", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "server_urls",
            },
        ),
        migrations.CreateModel(
            name="VitaliyOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sold_order_number", models.IntegerField()),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sellers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_telegram",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "auth_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentees",
                        to="main.sellers",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruits",
                        to="main.sellers",
                    ),
                ),
                (
                    "renter_lvl1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sellers_renters_lvl1",
                        to="main.sellers",
                    ),
                ),
                (
                    "renter_lvl2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sellers_renters_lvl2",
                        to="main.sellers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продавця",
                "verbose_name_plural": "Продавці",
                "db_table": "sellers",
            },
        ),
        migrations.CreateModel(
            name="SellerServerInterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest_rate",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.sellers"
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сервер продавця з ставкою",
                "verbose_name_plural": "Сервера продавців з ставками",
            },
        ),
        migrations.CreateModel(
            name="OffersForPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.TextField(max_length=255)),
                ("stock", models.IntegerField()),
                ("min_units_per_order", models.IntegerField()),
                ("active_rate", models.BooleanField(default=False)),
                ("percent_offset", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("face_to_face_trade", models.BooleanField(default=True)),
                ("mail_delivery", models.BooleanField(default=True)),
                ("auction_house", models.BooleanField(default=True)),
                ("delivery_online_hrs", models.IntegerField()),
                ("delivery_offline_hrs", models.IntegerField()),
                ("is_created_lot", models.BooleanField(default=False)),
                ("reserve_stock", models.IntegerField(default=0)),
                ("order_status", models.BooleanField(default=False, null=True)),
                (
                    "sellers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.sellers"
                    ),
                ),
                (
                    "server_urls",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пропозицію для розміщення на торгах",
                "verbose_name_plural": "Пропозиції для розміщення на торгах",
                "db_table": "offers_for_placement",
            },
        ),
        migrations.CreateModel(
            name="ChangeStockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField()),
                ("active_rate_record", models.BooleanField(default=False)),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.sellers"
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рядок",
                "verbose_name_plural": "Історія зміни стоку та статусу лотів",
            },
        ),
        migrations.CreateModel(
            name="SoldOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("bought_by", models.CharField(max_length=255)),
                ("character_name", models.CharField(max_length=255)),
                ("sold_order_number", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("sent_gold", models.IntegerField(db_default=0, null=True)),
                (
                    "price_unit",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "comission_fee",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "earned_without_admins_commission",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "owner_commission",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "technical_commission",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "to_be_earned",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("trade_mode", models.CharField(max_length=255)),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("send_message", models.BooleanField(default=False)),
                ("path_to_video", models.CharField(blank=True, max_length=255)),
                (
                    "download_video_status",
                    models.BooleanField(default=False, null=True),
                ),
                ("send_video_status", models.BooleanField(default=False, null=True)),
                ("charged_to_payment", models.BooleanField(default=False)),
                ("paid_in_salary", models.BooleanField(default=False)),
                ("paid_to_owner", models.BooleanField(default=False)),
                ("paid_to_technical", models.BooleanField(default=False)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.sellers"
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список замовлень для виплати",
                "verbose_name_plural": "Список замовлень для виплати",
                "db_table": "sold_orders",
            },
        ),
        migrations.CreateModel(
            name="CommissionBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentor_commissions",
                        to="main.sellers",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruiter_commissions",
                        to="main.sellers",
                    ),
                ),
                (
                    "renter_lvl1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_breakdowns_lvl1",
                        to="main.sellers",
                    ),
                ),
                (
                    "renter_lvl2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_breakdowns_lvl2",
                        to="main.sellers",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="main.sellers",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="main.soldorders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отримані комісії с замовлень",
                "verbose_name_plural": "Отримані комісії с замовлень",
            },
        ),
        migrations.CreateModel(
            name="AddOrder",
            fields=[],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.soldorders",),
        ),
        migrations.CreateModel(
            name="TopPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top1", models.IntegerField()),
                ("top5", models.IntegerField()),
                ("top10", models.IntegerField()),
                ("top20", models.IntegerField()),
                ("mean10", models.IntegerField()),
                ("mean20", models.IntegerField()),
                ("minimal", models.IntegerField()),
                ("mean10_lot", models.IntegerField()),
                ("mean20_lot", models.IntegerField()),
                ("double_minimal", models.IntegerField()),
                ("created_time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "server_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
            options={
                "db_table": "top_prices",
            },
        ),
    ]
