# Generated by Django 5.1.2 on 2024-11-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offersforplacement",
            name="currency",
            field=models.CharField(max_length=255),
        ),
    ]
