# Generated by Django 5.1.2 on 2025-02-07 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commissionbreakdown",
            name="mentor",
        ),
        migrations.RemoveField(
            model_name="commissionbreakdown",
            name="recruiter",
        ),
        migrations.RemoveField(
            model_name="commissionbreakdown",
            name="renter_lvl1",
        ),
        migrations.RemoveField(
            model_name="commissionbreakdown",
            name="renter_lvl2",
        ),
    ]
