# Generated by Django 5.1.2 on 2024-12-18 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sellers",
            old_name="id_discord",
            new_name="id_telegram",
        ),
        migrations.RemoveField(
            model_name="sellers",
            name="name_on_server",
        ),
    ]
