# Generated by Django 5.1.2 on 2024-12-18 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_id_discord_sellers_id_telegram_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="offersforplacement",
            table=None,
        ),
        migrations.AlterModelTable(
            name="serverurls",
            table=None,
        ),
        migrations.AlterModelTable(
            name="soldorders",
            table=None,
        ),
        migrations.AlterModelTable(
            name="topprices",
            table=None,
        ),
    ]
