# Generated by Django 5.1.2 on 2024-11-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_offersforplacement_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offersforplacement",
            name="price",
            field=models.TextField(max_length=255),
        ),
    ]
