# Generated by Django 5.1.2 on 2025-02-07 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_commissionbreakdown_mentor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellers",
            name="renter_lvl1",
        ),
        migrations.RemoveField(
            model_name="sellers",
            name="renter_lvl2",
        ),
        migrations.AddField(
            model_name="sellerserverinterestrate",
            name="renter_lvl1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellerserver_renters_lvl1",
                to="main.sellerserverinterestrate",
            ),
        ),
        migrations.AddField(
            model_name="sellerserverinterestrate",
            name="renter_lvl2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellerserver_renters_lvl2",
                to="main.sellerserverinterestrate",
            ),
        ),
    ]
