# Generated by Django 5.1.2 on 2024-12-18 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_offersforplacement_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="offersforplacement",
            table="offers_for_placement",
        ),
        migrations.AlterModelTable(
            name="serverurls",
            table="server_urls",
        ),
        migrations.AlterModelTable(
            name="soldorders",
            table="sold_orders",
        ),
        migrations.AlterModelTable(
            name="topprices",
            table="top_prices",
        ),
    ]
