# Generated by Django 5.1.2 on 2025-02-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_sellers_renter_lvl1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionbreakdown",
            name="charged_to_payment_commission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="commissionbreakdown",
            name="paid_in_salary_commission",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="commissionrates",
            name="renter_lvl1",
            field=models.DecimalField(
                decimal_places=3, default=0.05, max_digits=5, verbose_name="Renter 10%"
            ),
        ),
        migrations.AlterField(
            model_name="commissionrates",
            name="renter_lvl2",
            field=models.DecimalField(
                decimal_places=3, default=0.1, max_digits=5, verbose_name="Renter 5%"
            ),
        ),
        migrations.AlterField(
            model_name="sellerserverinterestrate",
            name="renter_lvl1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellerserver_renters_lvl1",
                to="main.sellerserverinterestrate",
                verbose_name="Renter 10%",
            ),
        ),
        migrations.AlterField(
            model_name="sellerserverinterestrate",
            name="renter_lvl2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellerserver_renters_lvl2",
                to="main.sellerserverinterestrate",
                verbose_name="Renter 5%",
            ),
        ),
    ]
