# Generated by Django 5.1.2 on 2025-02-08 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_commissionbreakdown_charged_to_payment_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerserverinterestrate",
            name="renter_lvl1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellerserver_renters_lvl1",
                to="main.sellers",
                verbose_name="Renter 10%",
            ),
        ),
        migrations.AlterField(
            model_name="sellerserverinterestrate",
            name="renter_lvl2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellerserver_renters_lvl2",
                to="main.sellers",
                verbose_name="Renter 5%",
            ),
        ),
    ]
