# Generated by Django 5.1.2 on 2024-12-18 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_offersforplacement_table_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soldorders",
            old_name="seller_id",
            new_name="seller",
        ),
        migrations.RenameField(
            model_name="soldorders",
            old_name="server_id",
            new_name="server",
        ),
    ]
