# Generated by Django 5.1.2 on 2025-02-22 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_sellerserverinterestrate_renter_lvl1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vitaliyorders",
            options={
                "verbose_name": "Замовлення Віталія",
                "verbose_name_plural": "Замовлення Віталія",
            },
        ),
        migrations.AddField(
            model_name="vitaliyorders",
            name="status",
            field=models.CharField(
                blank=True, default="REGISTERED", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sellerserverinterestrate",
            name="renter_lvl1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellers_renters_lvl1",
                to="main.sellers",
                verbose_name="Renter 10%",
            ),
        ),
        migrations.AlterField(
            model_name="sellerserverinterestrate",
            name="renter_lvl2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellers_renters_lvl2",
                to="main.sellers",
                verbose_name="Renter 5%",
            ),
        ),
    ]
