# Generated by Django 5.1.2 on 2024-11-15 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_sellers_id_auth_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sellers",
            old_name="id_auth_user",
            new_name="auth_user",
        ),
    ]
