# Generated by Django 5.1.2 on 2025-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_vitaliyorders_options_vitaliyorders_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offersforplacement",
            name="is_created_lot",
            field=models.BooleanField(default=True),
        ),
    ]
