# Generated by Django 5.1.2 on 2025-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_offersforplacement_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soldorders",
            name="sent_gold",
            field=models.IntegerField(db_default=0, null=True),
        ),
    ]
