# Generated by Django 5.1.2 on 2025-02-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0006_alter_vitaliyorders_options_vitaliyorders_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commissionbreakdown",
            name="order",
        ),
        migrations.AddField(
            model_name="commissionbreakdown",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commissionbreakdown",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
