# Generated by Django 5.1.2 on 2025-02-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_offersforplacement_is_created_lot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offersforplacement",
            old_name="is_created_lot",
            new_name="double_minimal_mode_status",
        ),
        migrations.AddField(
            model_name="soldorders",
            name="send_message_to_buyer_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
