# Generated by Django 5.1.2 on 2025-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            "0008_rename_is_created_lot_offersforplacement_double_minimal_mode_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="offersforplacement",
            name="double_minimal_mode_status",
            field=models.BooleanField(default=False),
        ),
    ]
