# Generated by Django 5.1.2 on 2025-03-04 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_commissionbreakdown_order_and_more"),
        ("main", "0009_alter_offersforplacement_double_minimal_mode_status"),
    ]

    operations = []
