# Generated by Django 5.1.2 on 2025-01-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_paymenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="soldorders",
            name="paid_in_salary",
            field=models.BooleanField(default=False),
        ),
    ]
