# Generated by Django 5.1.2 on 2025-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_soldorders_paid_in_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="soldorders",
            name="charged_to_payment",
            field=models.BooleanField(default=False),
        ),
    ]
