# Generated by Django 5.1.2 on 2025-01-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_alter_sellers_interest_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellers",
            name="id_telegram",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
