# Generated by Django 5.1.2 on 2025-01-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_sellers_id_telegram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellers",
            name="id_telegram",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="interest_rate",
            field=models.IntegerField(blank=True, default=75, null=True),
        ),
    ]
