# Generated by Django 5.1.2 on 2025-01-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_sellers_id_telegram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellers",
            name="interest_rate",
            field=models.IntegerField(default=75),
        ),
    ]
