# Generated by Django 5.1.2 on 2025-01-17 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_alter_sellers_interest_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soldorders",
            old_name="paid_in_salary",
            new_name="paid_in_seller_salary",
        ),
    ]
