# Generated by Django 5.1.2 on 2025-01-17 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_rename_paid_in_salary_soldorders_paid_in_seller_salary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soldorders",
            old_name="paid_in_seller_salary",
            new_name="paid_in_salary",
        ),
    ]
