# Generated by Django 5.1.2 on 2025-01-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_soldorders_paid_to_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellers",
            name="balance",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
