# Generated by Django 5.1.2 on 2025-01-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_alter_sellers_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellers",
            name="balance",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
