# Generated by Django 5.1.2 on 2025-01-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_alter_sellers_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soldorders",
            name="comission_fee",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="soldorders",
            name="earned_without_admins_commission",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="soldorders",
            name="owner_commission",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="soldorders",
            name="price_unit",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="soldorders",
            name="technical_commission",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="soldorders",
            name="to_be_earned",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="soldorders",
            name="total_amount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
