# Generated by Django 5.1.2 on 2025-01-26 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_alter_soldorders_comission_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitaliyOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("bought_by", models.CharField(max_length=255)),
                ("character_name", models.CharField(max_length=255)),
                ("sold_order_number", models.IntegerField()),
                ("quantity", models.IntegerField()),
                (
                    "price_unit",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "comission_fee",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "to_be_earned",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("trade_mode", models.CharField(max_length=255)),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.sellers"
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
        ),
    ]
