# Generated by Django 5.1.2 on 2025-01-28 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_remove_vitaliyorders_bought_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerServerInterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_rate", models.IntegerField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.sellers"
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
        ),
    ]
