# Generated by Django 5.1.2 on 2025-01-28 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_sellerserverinterestrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerserverinterestrate",
            name="interest_rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
