# Generated by Django 5.1.2 on 2025-01-31 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_alter_sellerserverinterestrate_interest_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellers",
            name="interest_rate",
        ),
    ]
