# Generated by Django 5.1.2 on 2025-01-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_changestockhistory_delete_paymenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="changestockhistory",
            name="stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
