# Generated by Django 5.1.2 on 2025-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_changestockhistory_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="changestockhistory",
            name="active_rate_record",
            field=models.BooleanField(default=False),
        ),
    ]
