# Generated by Django 5.1.2 on 2025-02-24 08:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0006_alter_vitaliyorders_options_vitaliyorders_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("bought_by", models.CharField(max_length=255)),
                ("character_name", models.CharField(max_length=255)),
                ("sold_order_number", models.BigIntegerField(unique=True)),
                ("quantity", models.IntegerField()),
                ("sent_gold", models.IntegerField(db_default=0, null=True)),
                (
                    "price_unit",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "earned_without_admins_commission",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "owner_commission",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "technical_commission",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("trade_mode", models.CharField(max_length=255)),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("send_message", models.BooleanField(default=False)),
                ("path_to_video", models.CharField(blank=True, max_length=255)),
                (
                    "download_video_status",
                    models.BooleanField(default=False, null=True),
                ),
                ("charged_to_payment", models.BooleanField(default=False)),
                ("paid_in_salary", models.BooleanField(default=False)),
                ("paid_to_owner", models.BooleanField(default=False)),
                ("paid_to_technical", models.BooleanField(default=False)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.sellers"
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serverurls",
                    ),
                ),
            ],
            options={
                "verbose_name": "Внутрішнє замовлення",
                "verbose_name_plural": "Внутрішні замовлення",
            },
        ),
    ]
