# Generated by Django 5.1.2 on 2025-02-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal_market", "0001_initial"),
        ("main", "0006_alter_vitaliyorders_options_vitaliyorders_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="internalorder",
            old_name="seller",
            new_name="internal_seller",
        ),
        migrations.AddField(
            model_name="internalorder",
            name="internal_buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_buyer",
                to="main.sellers",
            ),
        ),
    ]
