# Generated by Django 5.1.2 on 2025-02-24 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "internal_market",
            "0002_rename_seller_internalorder_internal_seller_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internalorder",
            name="bought_by",
        ),
    ]
