# Generated by Django 5.1.2 on 2025-02-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal_market", "0003_remove_internalorder_bought_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalorder",
            name="path_to_video",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="internalorder",
            name="sent_gold",
            field=models.IntegerField(blank=True, db_default=0, null=True),
        ),
        migrations.AlterField(
            model_name="internalorder",
            name="status",
            field=models.CharField(default="DELIVERING", max_length=255),
        ),
    ]
